@startuml

!include ./color_setting.pu

title Phase2 login.jsp、ログイン画面

actor 店員 #blue
participant login.jsp as jsp
participant LoginServlet as servlet
participant LoginDAO as dao
database "データベース" as db #red
participant HomeServlet

店員->>jsp:入力
activate jsp
jsp->servlet :loginButton押下でloginId,loginPass
deactivate jsp
activate servlet
servlet->dao:findUserLogin(loginId, loginPass);
activate dao
dao->db : user_login
activate db
db-->dao:login_id, login_password
deactivate db
dao-->servlet: loginId, loginPass
deactivate dao
servlet->servlet:IDとパスワードを確かめる

alt loginIdとloginPassが正しい場合
	servlet->HomeServlet: redirect
	activate HomeServlet
else loginIdとloginPassが間違えている場合
	servlet->jsp: エラーメッセージを出力
end

deactivate servlet
deactivate jsp
@enduml