@startuml

!include ./color_setting.pu

title Phase2 ordermanagement.jsp、注文管理画面

participant home.jsp
participant OrderManagementServlet
participant OrderManagementDAO
database "データベース" as DB #red
participant OrderManagementInfo
participant orderManagement.jsp

activate home.jsp
home.jsp->OrderManagementServlet:画面遷移
deactivate home.jsp

activate OrderManagementServlet
OrderManagementServlet->OrderManagementDAO:findAllOrder()
activate OrderManagementDAO
OrderManagementDAO->DB:order_details,multiple_topping,topping
activate DB
DB-->OrderManagementDAO:全部渡す
deactivate DB
OrderManagementDAO->OrderManagementInfo:
activate OrderManagementInfo
OrderManagementInfo-->OrderManagementDAO:orderManagementList
deactivate OrderManagementInfo
OrderManagementDAO-->OrderManagementServlet:orderManagementListをセッションスコープで送る
deactivate OrderManagementDAO
OrderManagementServlet->orderManagement.jsp:Listをjspに送る

activate orderManagement.jsp
orderManagement.jsp->OrderManagementServlet:severdButtonを押下
OrderManagementServlet->OrderManagementDAO:updateProvidedFlag(orderId)
activate OrderManagementDAO
OrderManagementDAO->DB:order_detailsのorder_flag = 1
activate DB
deactivate OrderManagementDAO
deactivate DB
OrderManegementServlet-->orderManagement.jsp:更新したデータを送る
deactivate OrderManagementServlet
orderManagement.jsp->:historyButtonを押下ServidHistoryServletへ遷移
orderManagement.jsp->:editButtonを押下EditOrderServletへ遷移
orderManagement.jsp->:homeButtonを押下HomeServletへ遷移

@enduml




