@startuml

!include ./color_setting.pu

title Phase2 ordermanegement.jsp、注文管理画面

participant OrderManegementServlet as servlet
participant OrderManegementDAO as dao
database "データベース" as db #red
participant OrderManegementInfo as model
participant orderManegement.jsp as jsp

->servlet:画面遷移
activate servlet
servlet->dao:findCurrentOrder()
activate dao
dao->db:order_details, multiple_topping, topping, product_details, product, table_sessions
activate db
db-->dao:全部渡す
deactivate db
dao->model:
activate model
model-->dao:orderManegementList
deactivate model
dao-->servlet:orderManegementListをセッションスコープで送る
deactivate dao
servlet->jsp:ListをJSPに送る

activate jsp
jsp->servlet:severdButtonを押下
servlet->dao:UpdateProvidedFlag(orderId)
activate dao
dao->db:order_details
deactivate dao
activate db
db->db:更新する
deactivate db
servlet-->jsp:更新したデータを送る
deactivate servlet
jsp->:historyButtonを押下ServidHistoryServletへ遷移
jsp->:editButtonを押下EditOrderServletへ遷移


@enduml




